language: cpp
sudo: required
dist: trusty
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - clang-3.5
        - zlib1g-dev
        - scons
script:
        - scons
        - scons debug=1
compiler:
        - clang
        - gcc
git:
        submodules: false
notifications:
        email:
            recipients:
                - macsim-dev-commits@googlegroups.com
            on_success: change
            on_failure: always
